config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/cookies', to: 'static_pages#cookies'
  get '/contact', to: 'static_pages#contact'
  get '/newuser', to: 'static_pages#newuser'

  resources :invites, only: [:new, :create]
  
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new'
  post '/your_endpoint', to: 'contacts#create'
  resources :ques_categories

  resources :questions do
    member do
      patch :make_unactive
    end
  end

  devise_for :users
  resources :future_messages do
    member do
      patch :publish 
    end
  end
  resources :future_message_alerts
  
  resources :questions do
    resources :answers
  end

  resources :young_people do
    resources :answers, only: [:index] 
    resources :future_messages, only: [:index]
  end

  resources :answers do
    delete :remove_media, on: :member
  end

  resources :questions do
    resources :change_requests, only: [:new, :create, :destroy, :index]
  end
  resources :change_requests, only: [:index, :show]

  resources :emotional_supports, only: [:new, :create, :index]
  resources :young_people
  resources :answer_alerts

  resources :bubbles
  resources :young_person_managements, param: :user_id do
    member do
      patch :passed_away
    end
  end

  resources :questions_controllers
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users do
    member do
      patch 'make_supporter_unactive'
      patch 'make_supporter_active'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :support, only: [:create]
      resources :questions, only: [:index, :show, :create, :update, :destroy]
      resources :change_requests, only: [:index, :show, :create, :destroy]
      resources :ques_categories, only: [:index, :show, :create, :destroy]
      resources :answers, only: [:index, :show, :create, :update, :destroy]
      resources :young_person_managements, only: [:index, :show]
      resources :bubbles, only: [:index, :show, :create, :update, :destroy] do
        resources :members, only: [:index, :show, :create, :update, :destroy]
        post 'assign', to: 'bubbles#assign'
        post 'unassign', to: 'bubbles#unassign'
      end
      resources :members, only: [:index, :show, :create, :update, :destroy]
    end
  end
  
  # Admin namespace for managing invites
  namespace :admin do
    resources :invites, only: [:index, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
    # other Devise routes
  end
end


app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id               :uuid             not null, primary key
#  active           :boolean          default(TRUE)
#  change           :boolean          default(FALSE)
#  content          :text
#  sensitivity      :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  ques_category_id :bigint
#
# Foreign Keys
#
#  fk_rails_...  (ques_category_id => ques_categories.id)
#
class Question < ApplicationRecord
  has_many :answers
  has_many :change_requests, dependent: :destroy
  belongs_to :ques_category, optional: true
  validates :content, presence: true
  validates :ques_category_id, presence: true
  validates :sensitivity, inclusion: { in: [true, false] }
  private

  def log_before_destroy
    Rails.logger.debug("Before destroy callback for Question with id: #{id}")
  end

end

app/controllers/api/v1/questions_controller.rb
# Api::V1::QuestionsController
# Controller for handling operations on the Question model.
# Provides RESTful methods to create, read, update, and delete questions.
#
# File Naming:
# The file name matches the class name (questions_controller.rb) following Rails conventions,
# which helps in maintaining the integrity if file names change, as Rails autoloads based on convention.

class Api::V1::QuestionsController < ApplicationController
  # Callback to set a question for actions that require finding a question by ID
  before_action :set_question, only: %i[show edit update destroy]

  # GET /questions
  # Retrieves and renders all questions in JSON format.
  def index
    @questions = Question.all
    render json: @questions
  end

  # GET /questions/1
  # Displays a single question.
  def show
  end

  # GET /questions/new
  # Prepares a new question object and fetches all question categories for the form.
  def new
    @question = Question.new
    @ques_categories = QuesCategory.all
  end

  # GET /questions/1/edit
  # Loads a question for editing.
  def edit
  end

  # POST /questions
  # Creates a new Question instance with parameters passed from the form.
  # Redirects to questions listing on success or re-renders the form on failure.
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_url, notice: 'Question was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /questions/1
  # Updates an existing question and redirects or re-renders based on outcome.
  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /questions/1
  # Attempts to destroy a question and handles exceptions.
  def destroy
    begin
      @question.destroy
      redirect_to questions_url, notice: 'Question was successfully destroyed.', status: :see_other
    rescue => e
      Rails.logger.error("Error destroying Question: #{e.message}")
      raise
    end
  end

  private

    # Finds a Question by id from parameters. Used as a before_action filter.
    def set_question
      @question = Question.find(params[:id])
    end

    # Filters and returns only permitted parameters.
    # Ensures only allowed attributes are passed to model.
    def question_params
      params.require(:question).permit(:content, :ques_category_id)
    end
end

# Comments regarding methods:
# Each public method includes a brief description of its function, parameters (if applicable), and what it returns or its side effects.
# Documentation:
# This file, as part of the API version 1 controllers, adheres to the naming conventions of the Rails framework.
# File explaining how to build and test this controller should be included in the project documentation, typically in a README or a designated docs directory.

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :ensure_authorized_for_action, only: [:index, :show, :edit, :destroy, :update]


  # GET /questions
  def index
    if current_user.admin?
      @questions = Question.all
    else
      @questions = Question.where(active: true)
    end
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @ques_categories = QuesCategory.all
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    @ques_categories = QuesCategory.all
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.ques_category_id.nil?
      redirect_to new_question_path, alert: "Question category is required" and return 
    end
    
    if @question.content.strip == ""
      redirect_to new_question_path, alert: "Question content is required" and return 
    end

    if @question.save
      redirect_to questions_path, notice: "Question was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to questions_path, notice: "Question was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

  end

  def make_unactive
    @question = Question.find(params[:id])
    
    if @question.update(active: false)
      redirect_to questions_url, notice: "Question was successfully deactivated.", status: :see_other
    else
      flash[:alert] = "Failed to deactivate Question."
      redirect_to questions_url, status: :see_other
    end
  end
  
  
  
  def request_change
    @question = Question.find(params[:id])
    @question.update(change: true)
    redirect_to @question, notice: 'Change request submitted successfully'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content , :ques_category_id, :sensitivity, :active)
    end

    def ensure_authorized_for_action
      case action_name.to_sym
      when :index, :show
        unless current_user.admin? || current_user.supporter? || current_user.young_person?
          redirect_to root_path, alert: "You are not authorized to access this page."
        end
      when :edit, :destroy, :update
        redirect_to root_path, alert: "You are not authorized to access this page." unless current_user.admin?
      end
    end
end

app/views/questions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@question) do |f|
  .card-body
    = f.input :content, label: "Question", required: true, input_html: { maxlength: 255 }
    = f.input :sensitivity, as: :boolean, label: "Sensitive"
    = f.association :ques_category, collection: @ques_categories.where(active: true), input_html: { class: 'mb-3 ques-category-field' }, label: "Question Category", required: true
  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', questions_path, class: 'btn btn-link ms-auto'

app/views/questions/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header Editing Question
      = render 'form'

app/views/questions/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Questions
    - if current_user && current_user.role == 'admin'
      = link_to 'New Question', new_question_path, class: 'btn btn-outline-secondary ms-auto'

  %table.table
    %thead
      %tr
        %th Question
        - if current_user && current_user.role != 'young_person'
          %th Sensitivity
        - if current_user && current_user.role == 'admin'
          %th Active
    %tbody
      - if current_user && current_user.role == 'young_person'
        - @questions.where(sensitivity: false).each do |question|
          %tr
            %td= question.content
            %td
              .btn-toolbar.float-end
                - if question.answers.any?
                  = link_to 'Show', question, class: 'btn btn-outline-secondary btn-sm'
                  = link_to 'Edit Answer', edit_question_answer_path(question, question.answers.first), class: 'btn btn-outline-primary ms-1 btn-sm'
                - else
                  = link_to 'Show', question, class: 'btn btn-outline-secondary btn-sm'
                  - if current_user && current_user.role == 'young_person'
                    = link_to 'Answer', new_question_answer_path(question), class: 'btn btn-outline-primary ms-1 btn-sm'
      - else
        - @questions.each do |question|
          %tr
            %td= question.content
            %td= question.sensitivity
            - if current_user && current_user.role == 'admin'
              %td= question.active
            %td
              .btn-toolbar.float-end
                = link_to 'Show', question, class: 'btn btn-outline-secondary btn-sm'
                - if current_user && current_user.role == 'admin'
                  = link_to 'Edit', edit_question_path(question), class: 'btn btn-bd-primary'
                  = link_to 'Deactivate', make_unactive_question_path(question), method: :patch, data: { confirm: 'Are you sure?' }
                - else 
                  = link_to 'Request Change', new_question_change_request_path(question), class: 'btn btn-bd-primary'



app/views/questions/new.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header New Question
      = render 'form'

app/views/questions/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Question details
      .card-body
        %dl.row.mb-0
        %dt.col-md-3 Name:
        %dd.col-md-9= @question.content
      .card-footer.d-flex
        - if current_user && current_user == 'admin'
          = link_to 'Edit', edit_question_path(@question), class: 'btn btn-link'
        = link_to 'Back', questions_path, class: 'btn btn-link ms-auto'