config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/cookies', to: 'static_pages#cookies'
  get '/contact', to: 'static_pages#contact'
  get '/newuser', to: 'static_pages#newuser'

  resources :invites, only: [:new, :create]
  
  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new'
  post '/your_endpoint', to: 'contacts#create'
  resources :ques_categories

  resources :questions do
    member do
      patch :make_unactive
    end
  end

  devise_for :users
  resources :future_messages do
    member do
      patch :publish 
    end
  end
  resources :future_message_alerts
  
  resources :questions do
    resources :answers
  end

  resources :young_people do
    resources :answers, only: [:index] 
    resources :future_messages, only: [:index]
  end

  resources :answers do
    delete :remove_media, on: :member
  end

  resources :questions do
    resources :change_requests, only: [:new, :create, :destroy, :index]
  end
  resources :change_requests, only: [:index, :show]

  resources :emotional_supports, only: [:new, :create, :index]
  resources :young_people
  resources :answer_alerts

  resources :bubbles
  resources :young_person_managements, param: :user_id do
    member do
      patch :passed_away
    end
  end

  resources :questions_controllers
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users do
    member do
      patch 'make_supporter_unactive'
      patch 'make_supporter_active'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :support, only: [:create]
      resources :questions, only: [:index, :show, :create, :update, :destroy]
      resources :change_requests, only: [:index, :show, :create, :destroy]
      resources :ques_categories, only: [:index, :show, :create, :destroy]
      resources :answers, only: [:index, :show, :create, :update, :destroy]
      resources :young_person_managements, only: [:index, :show]
      resources :bubbles, only: [:index, :show, :create, :update, :destroy] do
        resources :members, only: [:index, :show, :create, :update, :destroy]
        post 'assign', to: 'bubbles#assign'
        post 'unassign', to: 'bubbles#unassign'
      end
      resources :members, only: [:index, :show, :create, :update, :destroy]
    end
  end
  
  # Admin namespace for managing invites
  namespace :admin do
    resources :invites, only: [:index, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
    # other Devise routes
  end
end


app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :uuid             not null, primary key
#  bypass_invite_validation :boolean
#  current_sign_in_at       :datetime
#  current_sign_in_ip       :string
#  email                    :string
#  encrypted_password       :string           default(""), not null
#  last_sign_in_at          :datetime
#  last_sign_in_ip          :string
#  name                     :string
#  password                 :string
#  pronouns                 :string
#  remember_created_at      :datetime
#  reset_password_sent_at   :datetime
#  reset_password_token     :string
#  role                     :integer
#  sign_in_count            :integer          default(0), not null
#  status                   :integer
#  token                    :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_users_on_id                    (id) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  # Constants and Enums
  self.primary_key = 'id'
  enum role: { young_person: 0, loved_one: 1, supporter: 2, admin: 3 }

  # Validations
  before_save :downcase_email
  validates :password, presence: true, if: :password_required?
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :token, presence: true, unless: :bypass_invite_validation, on: :create
  validate :valid_invite_code, unless: :bypass_invite_validation, on: :create

  # Associations
  has_one :young_person
  has_one :bubble_member
  has_many :supporter_managements, foreign_key: "supporter_id", class_name: "YoungPersonManagement"
  has_many :young_people, through: :supporter_managements, source: :young_person
  has_many :young_person_managements, foreign_key: "young_person_id", class_name: "YoungPersonManagement"
  has_many :supporters, through: :young_person_managements, source: :supporter
  has_many :answers
  has_many :emotional_supports
  has_many :invites  # Assuming you have this association for managing related invites

  # Methods
  def downcase_email
    self.email = email.downcase
  end

  def password_required?
    password.present? || password_confirmation.present? || encrypted_password.blank?
  end

  def generate_invite_token
    SecureRandom.hex(10)  # Generates a random token for the invite
  end

  before_validation :assign_role_from_invite, on: :create

  # Assign role based on the invite token if present
  def assign_role_from_invite
    if token.present?
      invite = Invite.find_by(token: token)
      self.role = invite.role if invite && invite.expiration_date > Time.current
    end
  end

  private

  def valid_invite_code
    return if bypass_invite_validation
  
    invite = Invite.find_by(token: token)
    if invite.nil? || invite.expiration_date < Time.current || invite.used
      errors.add(:token, 'is invalid, expired, or has already been used')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_message, only: %i[ show edit update destroy ]

  def show
    @user = User.find(params[:id])
    if @user.role == 'young_person' && @user.young_person
      @current_managements = YoungPersonManagement.where(young_person_id: @user.young_person.user_id, active: :active)
      @previous_managements = YoungPersonManagement.where(young_person_id: @user.young_person.user_id, active: :unactive)
  
      @current_supporters = @current_managements.map do |management|
        supporter = Supporter.find_by(user_id: management.supporter_id)
        [supporter, management] if supporter
      end.compact
  
      @previous_supporters = @previous_managements.map do |management|
        supporter = Supporter.find_by(user_id: management.supporter_id)
        [supporter, management] if supporter
      end.compact
    else
      @current_supporters = []
      @previous_supporters = []
    end
  end
  
  

  def index
    @users = User.all
    # @user = User.find(params[:id])
    # if @user.role == 'young_person' && @user.young_person
    #   @current_managements = YoungPersonManagement.where(young_person_id: @user.young_person.user_id, active: true)
    #   @previous_managements = YoungPersonManagement.where(young_person_id: @user.young_person.user_id, active: false)
  
    #   @current_supporters = @current_managements.map do |management|
    #     supporter = Supporter.find_by(user_id: management.supporter_id)
    #     [supporter, management] if supporter
    #   end.compact
  
    #   @previous_supporters = @previous_managements.map do |management|
    #     supporter = Supporter.find_by(user_id: management.supporter_id)
    #     [supporter, management] if supporter
    #   end.compact
    # else
    #   @current_supporters = []
    #   @previous_supporters = []
    # end
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)

      if current_user != @user
        redirect_to @user, notice: "User was successfully updated."
      else
        redirect_to request.referer, notice: "User was successfully updated."
      end
    else
      render :edit
    end
  end
  
  def make_supporter_unactive
    @user = User.find(params[:id])
    @supporter = Supporter.find_by(user_id: @user.id)
    @supporter.update(active: false)
    redirect_to users_path
  end

  def make_supporter_active
    @user = User.find(params[:id])
    @supporter = Supporter.find_by(user_id: @user.id)
    @supporter.update(active: true)
    redirect_to users_path
  end
  

  def create
    @user = User.new(user_params)
    
    # Retrieve the invite based on the token provided at signup
    invite = Invite.find_by(token: params[:user][:token])
    
    if invite && invite.expiration_date > Time.now && !invite.used
      @user.role = invite.role # Assign the role from the invite
      invite.update(used: true) # Mark the invite as used
      if @user.save
        redirect_to root_url, notice: "User was successfully created with role #{invite.role}."
      else
        render :new
      end
    else
      @user.errors.add(:token, 'is invalid or has expired')
      render :new, alert: "Invalid or expired token."
    end
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_message
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def future_message_params
      params.require(:user).permit(:id, :content, :published_at, :user_id)
    end

    def user_params
      permitted_params = [:name, :email, :pronouns, :status, :role, :token] # Added :token to the list to capture it during sign-up.
    
      if params[:user][:password].present? || params[:user][:password_confirmation].present?
        password = params[:user][:password].strip
        params[:user][:password] = password
        permitted_params << :password
      else
        permitted_params << :password if @user.encrypted_password.present?
      end
    
      params.require(:user).permit(permitted_params)
    end
end

app/views/users/edit.html.haml
%h1 Edit User

= form_with(model: @user, local: true, class: "needs-validation") do |form|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .mb-3
    = form.label :name, class: "form-label"
    = form.text_field :name, class: "form-control"

  .mb-3
    = form.label :email, class: "form-label"
    = form.text_field :email, class: "form-control"


  .mb-3
    = form.label :password, class: "form-label"
    = form.password_field :password, class: "form-control"

  .mb-3
    = form.label :Pronouns, class: "form-label"
    = form.text_field :Pronouns, class: "form-control"

  .role-status-fields
    .field.hidden
      = form.hidden_field :role, value: @user.role

    .field.hidden
      = form.hidden_field :status, value: @user.status

  .actions
    = form.submit class: "btn btn-primary me-2"
    - if current_user && current_user.role == 'admin'
      = link_to 'Back', users_path, class: "btn btn-secondary"
    - elsif current_user && current_user.role == 'young_person'
      = link_to 'Back', questions_path, class: "btn btn-secondary"
    - elsif current_user && current_user.role == 'supporter'
      = link_to 'Back', young_person_managements_path, class: "btn btn-secondary"
    - else
      = link_to 'Back', answers_path, class: "btn btn-secondary"

:javascript
  ;(function() {
    'use strict'
    var forms = document.querySelectorAll('.needs-validation')
    Array.from(forms).forEach(function(form) {
      form.addEventListener('submit', function(event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }
        form.classList.add('was-validated')
      }, false)
    })
  })()

app/views/users/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Users

  %table.table
    %thead
      %tr
        %th Name
        %th Email
        %th Role
        %th Created At
        %th Status
        %th Actions

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.role
          %td= user.created_at.strftime("%Y-%m-%d")
          %td
            - if user.role == 'young_person' && YoungPerson.find_by(user_id: user.id).present?
              - if user.young_person.passed_away?
                %span.passed-away Passed Away
              - else
                %span.alive Alive
            - elsif user.role == 'supporter' && Supporter.find_by(user_id: user.id).present?
              - if Supporter.find_by(user_id: user.id).active?
                %span.active Active
              - else
                %span.unactive Unactive
          %td
            .btn-toolbar.float-end
            = link_to 'Show', user, class: 'btn btn-outline-secondary btn-sm'
            = link_to 'Edit', edit_user_path(user), class: 'btn btn-bd-primary'
            - if user.role == 'supporter' && Supporter.find_by(user_id: user.id).present?
              - if Supporter.find_by(user_id: user.id).active?
                = link_to 'Make Supporter Unactive', make_supporter_unactive_user_path(user), method: :patch, data: { confirm: 'Are you sure?' }
              - else
                = link_to 'Make Supporter active', make_supporter_active_user_path(user), method: :patch, data: { confirm: 'Are you sure?' }
            - if user.role == 'young_person' && YoungPerson.find_by(user_id: user.id).present?
              = link_to 'Assign Supporter', new_young_person_management_path(user_id: user.id), class: 'btn btn-bd-primary'

app/views/users/show.html.haml
%h1 User Details

%ul.list-group
  %li.list-group-item
    %strong Name:
    = @user.name
  %li.list-group-item
    %strong Email:
    = @user.email
  %li.list-group-item
    %strong Pronouns:
    = @user.Pronouns
  %li.list-group-item
    %strong Role:
    = @user.role

- if @user.role == 'young_person'
  %h2.mt-4 Current Supporter Details
  - if @current_supporters.any?
    %ul.list-group
      - @current_supporters.each do |supporter, management|
        %li.list-group-item
          %strong Name:
          = supporter.user.name
        %li.list-group-item
          %strong Email:
          = supporter.user.email
        %li.list-group-item
          %strong Commit:
          = management.commit
  - else
    %p No current supporter assigned now

  %h2.mt-4 Previous Supporter Details
  - if @previous_supporters.any?
    %ul.list-group
      - @previous_supporters.each do |supporter, management|
        %li.list-group-item
          %strong Name:
          = supporter.user.name
        %li.list-group-item
          %strong Email:
          = supporter.user.email
        %li.list-group-item
          %strong Commit:
          = management.commit
        %li.list-group-item
          %strong Date Ended:
          = management.updated_at.strftime("%Y-%m-%d")
  - else
    %p No previous supporter assigned before